backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:

  - name: "rooms"
    label: "Rooms"
    folder: "src/pages/rooms"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post-rooms"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Pretty Title 3", name: "prettytitle3", widget: "string", required: false}
      - {label: "Tab Key", name: "tabkey", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Room", name: "featuredroom", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "gallery"
    label: "Gallery"
    folder: "src/pages/gallery"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post-gallery"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string", required: false}
      - {label: "Link Text", name: "linktext", widget: "string", required: false}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Room Associated", name: "roomassociated", widget: "string", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
     